name: "Publish"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Install PNPM"
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "pnpm"
      - name: Setup dependencies
        run: pnpm install
      - name: Test before publish
        run: pnpm test:cli
      - name: Build library
        run: pnpm build:lib
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
